CREATE TABLE IF NOT EXISTS website_login_event (
  id BIGINT NOT NULL AUTO_INCREMENT,
  logged_in_at DATETIME(6) NOT NULL,
  user_id INT NULL,
  full_name VARCHAR(255) NULL,
  phone VARCHAR(20) NULL,
  email VARCHAR(100) NULL,
  user_category VARCHAR(32) NULL,
  user_type VARCHAR(64) NULL,
  roles VARCHAR(255) NULL,
  verified BIT NULL,
  enabled BIT NULL,
  account_status VARCHAR(32) NULL,
  remote_addr VARCHAR(64) NULL,
  country VARCHAR(64) NULL,
  region VARCHAR(64) NULL,
  city VARCHAR(64) NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  org VARCHAR(255) NULL,
  location_label VARCHAR(255) NULL,
  user_agent VARCHAR(512) NULL,
  source VARCHAR(64) NULL,
  user_snapshot TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_website_login_at (logged_in_at),
  KEY idx_website_login_user (user_id, logged_in_at),
  KEY idx_website_login_phone (phone)
);
